package projecto.projectofinal.datamodel.entities;
// Generated 31-may-2019 18:28:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Enparejamiento generated by hbm2java
 */
@Entity
@Table(name="enparejamiento"
    ,catalog="torneos"
)
public class Enparejamiento  implements java.io.Serializable {


     private Integer idEnparejamiento;
     private Fase fase;
     private int idP1;
     private String nombreP1;
     private String apellidosP1;
     private int idP2;
     private String nombreP2;
     private String apellidosP2;
     private String nombreEmparejamiento;

    public Enparejamiento() {
    }

    public Enparejamiento(Fase fase, int idP1, String nombreP1, String apellidosP1, int idP2, String nombreP2, String apellidosP2, String nombreEmparejamiento) {
       this.fase = fase;
       this.idP1 = idP1;
       this.nombreP1 = nombreP1;
       this.apellidosP1 = apellidosP1;
       this.idP2 = idP2;
       this.nombreP2 = nombreP2;
       this.apellidosP2 = apellidosP2;
       this.nombreEmparejamiento = nombreEmparejamiento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEnparejamiento", unique=true, nullable=false)
    public Integer getIdEnparejamiento() {
        return this.idEnparejamiento;
    }
    
    public void setIdEnparejamiento(Integer idEnparejamiento) {
        this.idEnparejamiento = idEnparejamiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fase", nullable=false)
    public Fase getFase() {
        return this.fase;
    }
    
    public void setFase(Fase fase) {
        this.fase = fase;
    }

    
    @Column(name="idP1", nullable=false)
    public int getIdP1() {
        return this.idP1;
    }
    
    public void setIdP1(int idP1) {
        this.idP1 = idP1;
    }

    
    @Column(name="nombreP1", nullable=false, length=32)
    public String getNombreP1() {
        return this.nombreP1;
    }
    
    public void setNombreP1(String nombreP1) {
        this.nombreP1 = nombreP1;
    }

    
    @Column(name="apellidosP1", nullable=false, length=64)
    public String getApellidosP1() {
        return this.apellidosP1;
    }
    
    public void setApellidosP1(String apellidosP1) {
        this.apellidosP1 = apellidosP1;
    }

    
    @Column(name="idP2", nullable=false)
    public int getIdP2() {
        return this.idP2;
    }
    
    public void setIdP2(int idP2) {
        this.idP2 = idP2;
    }

    
    @Column(name="nombreP2", nullable=false, length=32)
    public String getNombreP2() {
        return this.nombreP2;
    }
    
    public void setNombreP2(String nombreP2) {
        this.nombreP2 = nombreP2;
    }

    
    @Column(name="apellidosP2", nullable=false, length=64)
    public String getApellidosP2() {
        return this.apellidosP2;
    }
    
    public void setApellidosP2(String apellidosP2) {
        this.apellidosP2 = apellidosP2;
    }

    
    @Column(name="nombreEmparejamiento", nullable=false, length=32)
    public String getNombreEmparejamiento() {
        return this.nombreEmparejamiento;
    }
    
    public void setNombreEmparejamiento(String nombreEmparejamiento) {
        this.nombreEmparejamiento = nombreEmparejamiento;
    }




}


