package projecto.projectofinal.datamodel.entities;
// Generated 31-may-2019 18:28:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fase generated by hbm2java
 */
@Entity
@Table(name="fase"
    ,catalog="torneos"
)
public class Fase  implements java.io.Serializable {


     private Integer idFase;
     private Torneo torneo;
     private String nombreFase;
     private Set<Enparejamiento> enparejamientos = new HashSet<Enparejamiento>(0);
     private Set<Resultado> resultados = new HashSet<Resultado>(0);

    public Fase() {
    }

	
    public Fase(Torneo torneo, String nombreFase) {
        this.torneo = torneo;
        this.nombreFase = nombreFase;
    }
    public Fase(Torneo torneo, String nombreFase, Set<Enparejamiento> enparejamientos, Set<Resultado> resultados) {
       this.torneo = torneo;
       this.nombreFase = nombreFase;
       this.enparejamientos = enparejamientos;
       this.resultados = resultados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFase", unique=true, nullable=false)
    public Integer getIdFase() {
        return this.idFase;
    }
    
    public void setIdFase(Integer idFase) {
        this.idFase = idFase;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="torneo", nullable=false)
    public Torneo getTorneo() {
        return this.torneo;
    }
    
    public void setTorneo(Torneo torneo) {
        this.torneo = torneo;
    }

    
    @Column(name="nombreFase", nullable=false, length=32)
    public String getNombreFase() {
        return this.nombreFase;
    }
    
    public void setNombreFase(String nombreFase) {
        this.nombreFase = nombreFase;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fase")
    public Set<Enparejamiento> getEnparejamientos() {
        return this.enparejamientos;
    }
    
    public void setEnparejamientos(Set<Enparejamiento> enparejamientos) {
        this.enparejamientos = enparejamientos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fase")
    public Set<Resultado> getResultados() {
        return this.resultados;
    }
    
    public void setResultados(Set<Resultado> resultados) {
        this.resultados = resultados;
    }




}


