package projecto.projectofinal.datamodel.entities;
// Generated 31-may-2019 18:28:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Participante generated by hbm2java
 */
@Entity
@Table(name="participante"
    ,catalog="torneos"
)
public class Participante  implements java.io.Serializable {


     private Integer idParticipante;
     private Torneo torneo;
     private String nombre;
     private String apellidos;
     private int edad;

    public Participante() {
    }

    public Participante(Torneo torneo, String nombre, String apellidos, int edad) {
       this.torneo = torneo;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.edad = edad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idParticipante", unique=true, nullable=false)
    public Integer getIdParticipante() {
        return this.idParticipante;
    }
    
    public void setIdParticipante(Integer idParticipante) {
        this.idParticipante = idParticipante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="torneo", nullable=false)
    public Torneo getTorneo() {
        return this.torneo;
    }
    
    public void setTorneo(Torneo torneo) {
        this.torneo = torneo;
    }

    
    @Column(name="nombre", nullable=false, length=32)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellidos", nullable=false, length=64)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="edad", nullable=false)
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }




}


