package projecto.projectofinal.datamodel.entities;
// Generated 31-may-2019 18:28:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Resultado generated by hbm2java
 */
@Entity
@Table(name="resultado"
    ,catalog="torneos"
)
public class Resultado  implements java.io.Serializable {


     private Integer idResultado;
     private Fase fase;
     private int idPganador;
     private String nombreGanador;
     private String apellidosGanador;

    public Resultado() {
    }

    public Resultado(Fase fase, int idPganador, String nombreGanador, String apellidosGanador) {
       this.fase = fase;
       this.idPganador = idPganador;
       this.nombreGanador = nombreGanador;
       this.apellidosGanador = apellidosGanador;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idResultado", unique=true, nullable=false)
    public Integer getIdResultado() {
        return this.idResultado;
    }
    
    public void setIdResultado(Integer idResultado) {
        this.idResultado = idResultado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fase", nullable=false)
    public Fase getFase() {
        return this.fase;
    }
    
    public void setFase(Fase fase) {
        this.fase = fase;
    }

    
    @Column(name="idPGanador", nullable=false)
    public int getIdPganador() {
        return this.idPganador;
    }
    
    public void setIdPganador(int idPganador) {
        this.idPganador = idPganador;
    }

    
    @Column(name="nombreGanador", nullable=false, length=32)
    public String getNombreGanador() {
        return this.nombreGanador;
    }
    
    public void setNombreGanador(String nombreGanador) {
        this.nombreGanador = nombreGanador;
    }

    
    @Column(name="apellidosGanador", nullable=false, length=64)
    public String getApellidosGanador() {
        return this.apellidosGanador;
    }
    
    public void setApellidosGanador(String apellidosGanador) {
        this.apellidosGanador = apellidosGanador;
    }




}


