package projecto.projectofinal.datamodel.entities;
// Generated 31-may-2019 18:28:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Torneo generated by hbm2java
 */
@Entity
@Table(name="torneo"
    ,catalog="torneos"
)
public class Torneo  implements java.io.Serializable {


     private Integer idTorneo;
     private String nombreTorneo;
     private String deporte;
     private int cantidaParticipantes;
     private String estado;
     private Set<Participante> participantes = new HashSet<Participante>(0);
     private Set<Fase> fases = new HashSet<Fase>(0);

    public Torneo() {
    }

	
    public Torneo(String nombreTorneo, String deporte, int cantidaParticipantes, String estado) {
        this.nombreTorneo = nombreTorneo;
        this.deporte = deporte;
        this.cantidaParticipantes = cantidaParticipantes;
        this.estado = estado;
    }
    public Torneo(String nombreTorneo, String deporte, int cantidaParticipantes, String estado, Set<Participante> participantes, Set<Fase> fases) {
       this.nombreTorneo = nombreTorneo;
       this.deporte = deporte;
       this.cantidaParticipantes = cantidaParticipantes;
       this.estado = estado;
       this.participantes = participantes;
       this.fases = fases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTorneo", unique=true, nullable=false)
    public Integer getIdTorneo() {
        return this.idTorneo;
    }
    
    public void setIdTorneo(Integer idTorneo) {
        this.idTorneo = idTorneo;
    }

    
    @Column(name="nombreTorneo", nullable=false, length=64)
    public String getNombreTorneo() {
        return this.nombreTorneo;
    }
    
    public void setNombreTorneo(String nombreTorneo) {
        this.nombreTorneo = nombreTorneo;
    }

    
    @Column(name="deporte", nullable=false, length=32)
    public String getDeporte() {
        return this.deporte;
    }
    
    public void setDeporte(String deporte) {
        this.deporte = deporte;
    }

    
    @Column(name="cantidaParticipantes", nullable=false)
    public int getCantidaParticipantes() {
        return this.cantidaParticipantes;
    }
    
    public void setCantidaParticipantes(int cantidaParticipantes) {
        this.cantidaParticipantes = cantidaParticipantes;
    }

    
    @Column(name="estado", nullable=false, length=32)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="torneo")
    public Set<Participante> getParticipantes() {
        return this.participantes;
    }
    
    public void setParticipantes(Set<Participante> participantes) {
        this.participantes = participantes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="torneo")
    public Set<Fase> getFases() {
        return this.fases;
    }
    
    public void setFases(Set<Fase> fases) {
        this.fases = fases;
    }




}


